config:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
    username: override
    password: override
  jpa:
    ddl-auto: validate
    defer-datasource-initialization: false
  flyway:
    enabled: true
  integration:
    messaging:
      url: http://localhost:${wiremock.server.port}/messaging
      token-url: http://localhost:${wiremock.server.port}/token
      client-id: override
      client-secret: override
      sender:
        address: override
        name: override
        reply-to: override
    lifebuoy:
      url: http://localhost:${wiremock.server.port}/lifebuoy
      token-url: http://localhost:${wiremock.server.port}/token
      client-id: override
      client-secret: override
      apikey: override

